### PR TITLE
move promote_type call inside the generated function body

### LINKED ISSUE #207: Non-pure `@generated` functions cause hard-to-fix MethodErrors
This line: https://github.com/JuliaMath/Interpolations.jl/blob/839c1d3f6aaa855b4e384c40bd36adf2a72dcf93/src/b-splines/indexing.jl#L111

calls `promote_type` within the generator of a `@generated` function, which violates the rule that generated function generators must not observe any non-constant global state (in this case, it's observing the state of the set of existing methods). The problem is that this means that the generated code essentially has the set of `promote_type` methods baked in at the time the generator is first invoked. That creates some errors that are very hard to track down. For example, the following code: 

```julia
using Interpolations
ext = extrapolate(interpolate(eye(2), BSpline(Linear()), OnGrid()), Linear())
using ForwardDiff
x = ForwardDiff.Dual(1.0, 1.0)
ext[x, 2.5]
```

(with ForwardDiff master and Interpolations master) fails with: 

```
ERROR: LoadError: no promotion exists for ForwardDiff.Dual{Void,Float64,1} and Int64
Stacktrace:
 [1] promote_type(::Type{ForwardDiff.Dual{Void,Float64,1}}, ::Type{Int64}) at ./promotion.jl:161
 [2] promote_type(::Type{T} where T, ::Type{T} where T, ::Type{T} where T) at ./promotion.jl:127
 [3] gradient(...) at /home/rdeits/.julia/v0.6/Interpolations/src/b-splines/indexing.jl:111
 [4] macro expansion at /home/rdeits/.julia/v0.6/Interpolations/src/extrapolation/linear.jl:17 [inlined]
 [5] macro expansion at /home/rdeits/.julia/v0.6/Interpolations/src/extrapolation/extrap_prep.jl:89 [inlined]
 [6] macro expansion at /home/rdeits/.julia/v0.6/Interpolations/src/extrapolation/extrapolation.jl:57 [inlined]
 [7] getindex(::Interpolations.Extrapolation{Float64,2,Interpolations.BSplineInterpolation{Float64,2,Array{Float64,2},Interpolations.BSpline{Interpolations.Linear},Interpolations.OnGrid,0},Interpolations.BSpline{Interpolations.Linear},Interpolations.OnGrid,Interpolations.Linear}, ::ForwardDiff.Dual{Void,Float64,1}, ::Float64) at /home/rdeits/.julia/v0.6/Interpolations/src/extrapolation/extrapolation.jl:63
```

but if we just *move the ForwardDiff import earlier*, then everything is fine: 

```julia
using ForwardDiff
using Interpolations
ext = extrapolate(interpolate(eye(2), BSpline(Linear()), OnGrid()), Linear())
x = ForwardDiff.Dual(1.0, 1.0)
ext[x, 2.5]
```

This happens because if we import ForwardDiff first, then the baked-in version of the method table happens to include the promotion rules that ForwardDiff defines. 

The solution is just not to use promote_type inside the generator, but to just call it in the returned expression.

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #207 (at least for the particular case i showed there). 

I also changed the equivalent code in `hessian()`, although i think that code may have been broken already (`Array{TH` should have been `Array{$TH`). I'll see what the test coverage says. 

Anyway, please let me know if you think this is the right thing to do. If so, I should be able to construct a test to make sure #207 is really fixed.

### CODE REVIEW

File: src/b-splines/indexing.jl [hunk 1]
```diff
@@ -158,9 +160,11 @@ end
 
 @generated function hessian(itp::AbstractInterpolation{T,N}, xs...) where {T,N}
     n = count_interp_dims(itp,N)
-    TH = promote_type(T, [x <: AbstractArray ? eltype(x) : x for x in xs]...)
     xargs = [:(xs[$d]) for d in 1:length(xs)]
-    :(hessian!(Array{TH, 2}($n,$n), itp, $(xargs...)))
+    quote
+        TH = $(Expr(:call, :promote_type, T, [x <: AbstractArray ? eltype(x) : x for x in xs]...))
```
Comment (stevengj) [inline src/b-splines/indexing.jl]: The problem is that this constructs an array and does the type computations at runtime.  It may not be type-stable, either.  It seems like you'd be better off doing something like `TH = hessian_type(T, xs...)` with
```jl
hessian_type(T) = T
hessian_type(T, x::AbstractArray, xs...) = promote_type(eltype(x), hessian_type(T, xs...))
hessian_type(T, x, xs...) = promote_type(typeof(x), hessian_type(T, xs...))
```

Comment (rdeits) [reply src/b-splines/indexing.jl]: Are you sure? That array is constructed inside the generator, not in the run-time code, and all the branching likewise happens inside the generator. I'm a fan of the lisp-y recursion trick anyway, but I'm pretty sure this case will work as-is.

Comment (stevengj) [reply src/b-splines/indexing.jl]: Oh, right, I misread your code — you're right, ther eshould continue to be no runtime cost here.

**Comment by rdeits** [comment]
Rebased. Good to go?

**Comment by rdeits** [comment]
Re-rebased after #197 :slightly_smiling_face:
